"""
Visual constants used to create game levels
"""

# Constants
# SCREEN_WIDTH = 1000
# SCREEN_HEIGHT = 650
# SCREEN_TITLE = "PORTaLAND"

SCREEN_TITLE = "PORTaLAND"

TILE_SIZE = 32

SCREEN_GRID_WIDTH = 25
SCREEN_GRID_HEIGHT = 20

SCREEN_WIDTH = TILE_SIZE * SCREEN_GRID_WIDTH
SCREEN_HEIGHT = TILE_SIZE * SCREEN_GRID_HEIGHT

TILE_SCALING = 2.0

STARTING_X = TILE_SIZE * 7
STARTING_Y = TILE_SIZE * 3
