"""
Visual constants used to create game levels
"""

# Constants
# SCREEN_WIDTH = 1000
# SCREEN_HEIGHT = 650
# SCREEN_TITLE = "PORTaLAND"

SCREEN_TITLE = "PORTaLAND"

TILE_SIZE = 32

PLAYER_SCALING = 1.5
TILE_SCALING = 2.0
SCALING_LASER = 0.8

SPRITE_SIZE = int(TILE_SIZE * PLAYER_SCALING)

SCREEN_GRID_WIDTH = 25
SCREEN_GRID_HEIGHT = 20

SCREEN_WIDTH = TILE_SIZE * SCREEN_GRID_WIDTH
SCREEN_HEIGHT = TILE_SIZE * SCREEN_GRID_HEIGHT

STARTING_X = TILE_SIZE * 7
STARTING_Y = TILE_SIZE * 3
